### ISSUE TITLE
Readme with gif

### ISSUE THREAD

**Issue by brianebeling** [Chris-Johnston/CyberPumpkin#1]
Yo, what's up Chris?

Haven't heard from you in quite some while. I hope you are doing well, how about including a gif of the animation in the readme?

Love these small projects, fun stuff :P

**Comment by Chris-Johnston** [comment]
Hey Brian! You read my mind (or my comments). I could only record so much of the pumpkin before it ended up getting moldy, but I've added a recording of the ping test to the readme as a GIF

I've been otherwise pretty busy, but the small projects like this are nice as a fun distraction.
